[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://staticjscms.netlify.app/*"
  to = "https://www.staticcms.org/:splat"
  status = 301

[[redirects]]
  from = "https://staticjscms.netlify.app/"
  to = "https://www.staticcms.org/"
  status = 301
